# Example Site settings

#google_analytics: UA-NNNNNNNN-N

#header_pages:
#  - index.md
#  - about.md

#footer: 'follow us on <a href="https://twitter.com/">twitter</a>'

#style: light # dark (default) or light
#listen_for_clients_preferred_style: true # true or false (default)

header_pages:
  - index.md
  - tags.html
  - categories.html
  - about.markdown


style: hacker # dark (default), light or hacker
#listen_for_clients_preferred_style: true # false (default) or true

footer: 'fork me on <a href="https://github.com/bot66">github</a>'

plugins:
  - jekyll-seo-tag
